### ISSUE TITLE
ZBTB16 & SLC39A1: exploration for MorphMap paper

### ISSUE THREAD

**Issue by AnneCarpenter** [broadinstitute/2023_12_JUMP_data_only_vignettes#12]
From #7  we see that ZBTB16 & SLC39A1 are strongly anti-correlated in ORF data and CRISPR data, and it's novel (not seen in Evotec KG).

Zinc finger and BTB domain-containing protein 16
SLC: Zinc transporter

Tons of ppl study SLCs in general, but none came up for SLC39A1 specifically. So I went the ZBTB16 route instead. Here is a link to active NIH grants that have ZBTB16 in them if we need a backup: https://reporter.nih.gov/search/AAbEtq4H8Uyo8KnZoZOIoQ/projects?projects=Active

I emailed heechang@umich.edu today:

Hello,
I found that you might study ZBTB16 based on your [NIH grant](https://reporter.nih.gov/search/AAbEtq4H8Uyo8KnZoZOIoQ/project-details/10649509) "Regulation of metabolic pathways in NKT cells" (it came up in a search though ZBTB16 isn't in the abstract). I wonder if our recent results might spark a collaboration?

To summarize a lot of work, we knocked down and overexpressed genes one by one in U2OS human cells, and then clustered the genes based on having similar *morphological* impact (using the Cell Painting microscopy assay that labels major organelles).

We found ZBTB16 (Zinc finger transcription factor) has the opposite morphological impact as SLC39A1 (Zinc transporter), in both overexpression and CRISPR knockdown data. It seems this connection is novel?

If so, we would be delighted to work together if you'd like to design an experiment to followup/confirm the connection and add to a paper we are beginning to write up about the large dataset. It always helps in such papers to make a new discovery that can be confirmed (even if it's not a dramatic finding).

All the best, please let me know if you would like to talk further!

Cheers,
Anne

**Comment by niranjchandrasekaran** [comment]
We will discuss the exploration of the story in [this doc](https://docs.google.com/document/d/1zKkDpBWbb3NnQhlX34LEWuuZxy5Rotre5uuuBMTxvxY/edit?usp=sharing) (private link)

**Comment by AnneCarpenter** [comment]
Prompt for plex if we need it "Carefully review all 20 top results across all categories. These results represent perturbations which result in modulation of similar processes to a perturbation of interest. Based on the biological processes that are most shared across all of these results what do you think are the most likely biological processes that are modulated by the perturbation of interest? Please be specific."

**Comment by jgaetz-plex** [comment]
A [Plex search](https://plexsearch.com/search#tab=pathway&ids=entrezgene%3A100043314&ids=entrezgene%3A100287902&ids=entrezgene%3A100362102&ids=entrezgene%3A102553763&ids=entrezgene%3A10533&ids=entrezgene%3A11343&ids=entrezgene%3A114664&ids=entrezgene%3A114845&ids=entrezgene%3A116724&ids=entrezgene%3A12322&ids=entrezgene%3A128497&ids=entrezgene%3A13823&ids=entrezgene%3A14381&ids=entrezgene%3A14584&ids=entrezgene%3A14619&ids=entrezgene%3A149986&ids=entrezgene%3A153328&ids=entrezgene%3A15382&ids=entrezgene%3A160728&ids=entrezgene%3A16599&ids=entrezgene%3A170758&ids=entrezgene%3A171482&ids=entrezgene%3A18214&ids=entrezgene%3A18261&ids=entrezgene%3A20018&ids=entrezgene%3A2009&ids=entrezgene%3A201633&ids=entrezgene%3A203413&ids=entrezgene%3A213233&ids=entrezgene%3A215210&ids=entrezgene%3A216225&ids=entrezgene%3A21685&ids=entrezgene%3A21877&ids=entrezgene%3A219869&ids=entrezgene%3A225049&ids=entrezgene%3A23136&ids=entrezgene%3A232334&ids=entrezgene%3A232679&ids=entrezgene%3A233890&ids=entrezgene%3A234138&ids=entrezgene%3A235320&ids=entrezgene%3A238021&ids=entrezgene%3A239250&ids=entrezgene%3A23945&ids=entrezgene%3A241846&ids=entrezgene%3A24377&ids=entrezgene%3A24834&ids=entrezgene%3A2539&ids=entrezgene%3A25400&ids=entrezgene%3A254956&ids=entrezgene%3A25503&ids=entrezgene%3A25794&ids=entrezgene%3A26362&ids=entrezgene%3A26548&ids=entrezgene%3A26549&ids=entrezgene%3A2706&ids=entrezgene%3A27173&ids=entrezgene%3A27393&ids=entrezgene%3A283629&ids=entrezgene%3A285596&ids=entrezgene%3A288591&ids=entrezgene%3A289456&ids=entrezgene%3A28958&ids=entrezgene%3A28972&ids=entrezgene%3A290467&ids=entrezgene%3A290555&ids=entrezgene%3A290811&ids=entrezgene%3A29254&ids=entrezgene%3A29362&ids=entrezgene%3A29578&ids=entrezgene%3A296957&ids=entrezgene%3A297523&ids=entrezgene%3A299897&ids=entrezgene%3A303741&ids=entrezgene%3A304530&ids=entrezgene%3A30791&ids=entrezgene%3A308409&ids=entrezgene%3A308444&ids=entrezgene%3A312647&ids=entrezgene%3A313418&ids=entrezgene%3A317258&ids=entrezgene%3A3178&ids=entrezgene%3A328258&ids=entrezgene%3A328401&ids=entrezgene%3A330177&ids=entrezgene%3A353227&ids=entrezgene%3A360518&ids=entrezgene%3A360762&ids=entrezgene%3A361206&ids=entrezgene%3A361986&ids=entrezgene%3A362122&ids=entrezgene%3A362696&ids=entrezgene%3A362783&ids=entrezgene%3A381812&ids=entrezgene%3A390443&ids=entrezgene%3A394266&ids=entrezgene%3A403187&ids=entrezgene%3A4921&ids=entrezgene%3A498000&ids=entrezgene%3A499943&ids=entrezgene%3A500324&ids=entrezgene%3A500820&ids=entrezgene%3A51082&ids=entrezgene%3A51170&ids=entrezgene%3A51274&ids=entrezgene%3A51347&ids=entrezgene%3A51530&ids=entrezgene%3A52469&ids=entrezgene%3A54148&ids=entrezgene%3A55080&ids=entrezgene%3A558&ids=entrezgene%3A57217&ids=entrezgene%3A57708&ids=entrezgene%3A5881&ids=entrezgene%3A6358&ids=entrezgene%3A654231&ids=entrezgene%3A684304&ids=entrezgene%3A68519&ids=entrezgene%3A685781&ids=entrezgene%3A69019&ids=entrezgene%3A7008&ids=entrezgene%3A7083&ids=entrezgene%3A71099&ids=entrezgene%3A71148&ids=entrezgene%3A7227&ids=entrezgene%3A74244&ids=entrezgene%3A75495&ids=entrezgene%3A75642&ids=entrezgene%3A7704&ids=entrezgene%3A79724&ids=entrezgene%3A80185&ids=entrezgene%3A80207&ids=entrezgene%3A815&ids=entrezgene%3A83862&ids=entrezgene%3A83925&ids=entrezgene%3A84189&ids=entrezgene%3A84766&ids=entrezgene%3A9686&ids=entrezgene%3A9945) with the 52 most similar ORFs to this cluster does not give any strong hypotheses for a functional connection.

**Comment by AnneCarpenter** [comment]
Ok, thank you. This one is written into the paper as follows and we needn't do more research on it (although Jed, it's a bit odd your search didn't uncover what's shown below in your GO annotation - oh, I guess because you searched 52 genes rather than just the 2 genes!):

"Our analysis also uncovered a strong correlation in both ORF and CRISPR profiles between genes SLC39A1 and ZBTB16 ([Figure 8](https://docs.google.com/document/d/160QYCeJXMJMPgvYcirkkKaY99r6dZq6FMqYGE61CfFc/edit#fig_heatmap) b and c). Notably, while this connection lacks direct evidence in literature, it is supported by orthogonal evidence in the form of common Gene Ontology annotations, including Embryo development, Appendage development, Embryonic morphogenesis and Skeletal system development."

**Comment by jgaetz-plex** [comment]
Right. With the 52 gene set there are some shared GO annotations, but nothing I would consider strongly linking this group of genes.

**Comment by AnneCarpenter** [comment]
Great. Is it silly to search Plex with just the two genes to see if there's more concrete links between the two? I was surprised the Knowledge graph score was so high for genes that only share GO terms, so I wonder if we missed some other data/literature out there.

**Comment by jgaetz-plex** [comment]
It's not silly; it could potentially identify some connection we aren't aware of. For the [2-gene search](https://plexsearch.com/search?ids=entrezgene%3A27173&ids=entrezgene%3A7704#tab=target), we might be interested in results with 2 direct connections in any of the gene/protein set categories (Protein Domains, Motifs, Publications, etc). There are very few results where both genes are connected. There are a few Publications results, but they all topically broad and include large numbers of genes, making the co-occurrence of these two genes not notable.

**Comment by AnneCarpenter** [comment]
ok, great! We can leave the text as-is in the main paper gdoc, then.

**Comment by niranjchandrasekaran** [comment]
This story was included in the morphmap paper
