### ISSUE TITLE
Cluster GPR176, TSC22D1, DPAGT1, CHRM4: exploration for MorphMap paper (ORF+CRISPR)

### ISSUE THREAD

**Issue by AnneCarpenter** [broadinstitute/2023_12_JUMP_data_only_vignettes#15]
This cluster was found in #7 as strong (+/-) correlation in both ORF and CRISPR but not (completely) strongly connected in the KG. 

Looking across ORF and CRISPR plots there, there are a few other adjacent genes we should consider adding to this and then figure out a story for them (if needed, contacting a biologist who studies some subset of these genes).

<img width="407" alt="Screenshot 2024-01-18 at 12 25 47 PM" src="https://github.com/broadinstitute/2023_12_JUMP_data_only_vignettes/assets/1213811/0d4260c4-d844-488e-99ef-d3f742244b3b">

**Comment by niranjchandrasekaran** [comment]
[Notebook 1](https://github.com/jump-cellpainting/2024_Chandrasekaran_Morphmap/blob/9d5d8e2d220e6b62f46618420c6e113dac42e99b/07.compute-cosine-similarities/13.explore-GPR176-CHRM4-connections.ipynb)

`LZTS2` is not present in the CRISPR dataset. Here are the remaining genes

### ORF
![ORF-connections-GPR176-CHRM4-TSC22D1-MYT1-LZTS2](https://github.com/user-attachments/assets/bc297d40-6b8b-462a-9b9c-ca5a66c97058)


### CRISPR
![CRISPR-connections-GPR176-CHRM4-TSC22D1-MYT1](https://github.com/user-attachments/assets/47e4d1fa-49f9-41e3-be08-560bdf6aedbd)

**Comment by niranjchandrasekaran** [comment]
We will discuss the exploration of the story in [this doc](https://docs.google.com/document/d/1zKkDpBWbb3NnQhlX34LEWuuZxy5Rotre5uuuBMTxvxY/edit?usp=sharing) (private link)

**Comment by jgaetz-plex** [comment]
Knock-down of Musashi-1 (MSI1) in SU_MB002 medulloblastoma cells has been reported to lead to down-regulation of GPR176, CHRM4, and TSC22D1 and up-regulation of MYT1 by RNA seq analysis, mirroring our observed correlations ([Kameda-Smith et al](https://pubmed.ncbi.nlm.nih.gov/36473869/)). MSI1 may play an essential role in nervous system development ([Kameda-Smith et al](https://pubmed.ncbi.nlm.nih.gov/36473869/)). Additionally, GPR176, CHRM4, and TSC22D1 are reported to be down-regulated in Alzheimer's Disease (AD) associated TREM2 variants ([Liu et al JExpMed2020](https://pubmed.ncbi.nlm.nih.gov/32941599/)).

**Comment by jgaetz-plex** [comment]
https://plexsearch.com/search?ids=entrezgene%3A11245&ids=entrezgene%3A1132&ids=entrezgene%3A117257&ids=entrezgene%3A12672&ids=entrezgene%3A17932&ids=entrezgene%3A21807&ids=entrezgene%3A226154&ids=entrezgene%3A25111&ids=entrezgene%3A362291&ids=entrezgene%3A365468&ids=entrezgene%3A381413&ids=entrezgene%3A4661&ids=entrezgene%3A498545&ids=entrezgene%3A84445&ids=entrezgene%3A8848#tab=gds

**Comment by AnneCarpenter** [comment]
Great, this paragraph has been finished and put in the main text. Presumably @niranjchandrasekaran needs to assemble the final figures into the main paper, so leaving it to him to close this issue when ready.

**Comment by niranjchandrasekaran** [comment]
This story was included in the morphmap paper
