### ISSUE TITLE
FOXO3/TGFB short mention (CRISPR)

### ISSUE THREAD

**Issue by afermg** [broadinstitute/2023_12_JUMP_data_only_vignettes#22]
Moved from https://github.com/jump-cellpainting/morphmap/issues/160
-----
From a mail chain with some startup looking to use FOXO3 as a therapeutic target.

    Probably like two sentences in the final paper saying something like "We first looked at well-known proteins, starting with TGFb, and we saw FOXO3 and a bunch of other well-known pathway members and interactors were strongly correlated/anto-correlated (fig x)"

        have compounds that impact FOXO3 but not sure what is the direct target
        Him seeing TGFb on the bottom of the list of FOXO3 is very exciting because involved in fibrosis
        FOXO3/TGFb relationship well known: totally fine to include this vignette in MorphMap paper, not confidential

Found an already validated anticorrelated pair, we should add a bit of info on this FOXO3/TGFB business.
@[AnneCarpenter](https://github.com/AnneCarpenter)
AnneCarpenter commented [Jan 24, 2024](https://github.com/jump-cellpainting/morphmap/issues/160#issuecomment-1908588694)

Is it possible to move this to 2023_12_JUMP_data_only_vignettes repo? I didn't have permissions (maybe it's not possible). That will help me to track it better. @afermg

**Comment by niranjchandrasekaran** [comment]
This was included in the Morphmap paper.
