### ISSUE TITLE
MYT1-RNF41 exploration for MorphMap paper (ORF)

### ISSUE THREAD

**Issue by afermg** [broadinstitute/2023_12_JUMP_data_only_vignettes#3]
From: Anne Carpenter <anne@broadinstitute.org>
Date: Fri, Dec 1, 2023 at 2:44 PM

Hi Ardigen/Ksilink,
Using this attached plot from Ardigen of the top 25 most anti-correlated pairs, I saw MYT1-RNF41.

So, I found someone who studies MYT1 who is willing to collaborate. We told her that MYT1 has the 'opposite' profile to RNF41 and she looked in some unpublished data of hers and she sees that MYT1 (a repressor) binds to the promoter of RNF41! Neat! (please keep that confidential)

She may design further followups to add to MorphMap. I'm not sure it's necessary but it may help to have more info about MYT1:

How feasible is it to generate a list of top-10 genes that correlate/anti-correlate to MYT1 (with the correlation values so we see the strength)? This was from the CRISPR data, but it looks like we tested the gene in ORFs too so we could create both sets of lists.

We'd also like to tell her what is the morphology diff for MYT1 vs neg controls, but I think we will start by pulling up a few images on our side, because that is a hard Q to answer via informatics (we wrote a blog post of steps but it's fairly unsatisfying/time-consuming). 

<img width="644" alt="Screenshot 2023-12-01 at 2 33 44 PM" src="https://github.com/jump-cellpainting/morphmap/assets/1210428/d6d9e0b9-d61d-4201-af7c-95cbddc23901">

----------

From: Anne Carpenter <anne@broadinstitute.org>
Date: Tue, Dec 5, 2023 at 11:52 AM

I'm adding Alán on our team who has been working on this connection specifically. He pulled images for us but we didn't see anything dramatic by eye (there is a LOT of variation from one replicate to the next, which makes this harder and is discouraging but I guess it explains batch effects we see in the data!)

Alán found the attached relationships at the replicate level in CRISPR data (Harmony-corrected). We expected a negative correlation between the two genes, and it looks like we see that for 2 replicates of RNF41 but not all of them. That is rather odd, as is the fact that a single replicate of the MYT1s is anti-correlated with ALL of the RNF41.

I'm guessing this pair of genes was in the top-25 of Ardigen's "negative correlation" list because after averaging (median, I think) it was still a strong relationship, but still it's a little surprising. 

Ardigen, can you confirm you see a similar thing with replicates? I believe you are using the exact same Harmony-corrected profiles. 

I guess this evidence is strong enough to continue working on this pair even though a few replicates were not consistent... Ksilink have you seen anything odd going on between replicates in the data in general? 

I imagine this could either be:

1. bad batch effects that weren't corrected enough.
2. batch effects that were corrected too much, in a way that introduced errors.
3. some replicates (maybe some whole batches) just didn't CRISPR-knock-down effectively for technical reasons.

I welcome any thoughts anyone has on the matter! I will proceed to meet with the scientist in ~24 hours by zoom to see if she has some experiments to run, or if we can include the unpublished data she has already. 

![correlations_pearson_harmony_myt1_rnf42](https://github.com/jump-cellpainting/morphmap/assets/1210428/ae5b6dc6-2d60-49ec-9d75-b09f65c17131)

----------

Edit by Niranj: Code for generating the following list: https://github.com/jump-cellpainting/morphmap/blob/c3393f985cb0a2c1a906ca8438f105eb785ce4de/12.explore-correlations-anticorrelations/4.explore-myt1.ipynb

From: Niranj Chandrasekaran <csriniva@broadinstitute.org>
Date: Wed, Dec 6, 2023 at 6:45 PM

I created the list of top correlated and anti correlated genes in the ORF dataset. RNF41 appears at the top. I have not checked whether the results look different at the replicate level or not.

**Top correlated**

Metadata_broad_sample_1 | Metadata_broad_sample_2 | Cosine_similarity | Gene_1 | Gene_2
-- | -- | -- | -- | --
ccsbBroad304_10986 | ccsbBroad304_04392 | 0.65285605 | MYT1 | LZTS2
ccsbBroad304_10986 | ccsbBroad304_01581 | 0.62539047 | MYT1 | SOX15
ccsbBroad304_10986 | ccsbBroad304_10195 | 0.59890395 | MYT1 | LGALS9C
ccsbBroad304_10986 | ccsbBroad304_09189 | 0.57654506 | MYT1 | LZTS2
ccsbBroad304_10986 | ccsbBroad304_04393 | 0.55127573 | MYT1 | LCOR
ccsbBroad304_10986 | ccsbBroad304_11168 | 0.53719974 | MYT1 | TACC1
ccsbBroad304_10986 | ccsbBroad304_13816 | 0.5334892 | MYT1 | ASCL2
ccsbBroad304_10986 | ccsbBroad304_15450 | 0.529622 | MYT1 | HNRNPC
ccsbBroad304_10986 | ccsbBroad304_01085 | 0.529373 | MYT1 | NEUROD1
ccsbBroad304_10986 | ccsbBroad304_04658 | 0.52150875 | MYT1 | ERMAP

**Top anti-correlated**

Metadata_broad_sample_1 | Metadata_broad_sample_2 | Cosine_similarity | Gene_1 | Gene_2
-- | -- | -- | -- | --
ccsbBroad304_10986 | ccsbBroad304_02346 | -0.6578171 | MYT1 | RNF41
ccsbBroad304_10986 | ccsbBroad304_11513 | -0.5148919 | MYT1 | DDX17
ccsbBroad304_10986 | ccsbBroad304_00946 | -0.512445 | MYT1 | LMNA
ccsbBroad304_10986 | ccsbBroad304_10479 | -0.4869117 | MYT1 | FAM81A
ccsbBroad304_10986 | ccsbBroad304_04413 | -0.4827406 | MYT1 | TRIM55
ccsbBroad304_10986 | ccsbBroad304_04404 | -0.460314 | MYT1 | TUBB6
ccsbBroad304_10986 | ccsbBroad304_08471 | -0.4582101 | MYT1 | AGGF1
ccsbBroad304_10986 | ccsbBroad304_04931 | -0.4466559 | MYT1 | FOXR2
ccsbBroad304_10986 | ccsbBroad304_04798 | -0.4455448 | MYT1 | KRT40
ccsbBroad304_10986 | ccsbBroad304_16059 | -0.444838 | MYT1 | CCDC74A

----------

From: Anne Carpenter <anne@broadinstitute.org>
Date: Thu, Dec 7, 2023 at 10:04 AM

Oh, awesome! I didn't even dare hope they were both *existing* in the ORF dataset.

So now these two genes are anti-correlated in both CRISPR and ORF data; that is a nice story (and makes me much less worried about the inconsistent replicates in CRISPR). 

FYI, I've started to write up this section of the paper in the MorphMap draft at the end of the results [here](https://docs.google.com/document/d/160QYCeJXMJMPgvYcirkkKaY99r6dZq6FMqYGE61CfFc/edit#heading=h.b18er0xmu87g). I talked to the researcher (Sui Wang) and she says she can have a lab member make constructs to do a reporter assay to add to this section in addition to the promoter-binding unpublished results I mentioned before.

GIven how clean a story this is, I think for the paper we ought to make a full list of gene pairs that have this behavior: anti-correlating in both CRISPR and ORF datasets. This is the strongest evidence for them regulating each other and would be a nice finding (with one such pair, MYT1+RNF41, confirmed).

**Comment by niranjchandrasekaran** [comment]
This is included in the morphmap paper
