### ISSUE TITLE
Explore vignettes

### ISSUE THREAD

**Issue by niranjchandrasekaran** [broadinstitute/2023_12_JUMP_data_only_vignettes#37]
@afermg, @jessica-ewald 

The vignettes that need to be further explored are #4, #9, #15 and #16.

The colors in the heatmaps in those issues are the percentile of cosine similarities (dark blue -> 1 and dark red -> 0). The text in the heatmaps are the scores from the Knowledge Graph. A value greater than 0.4 suggests that there is some existing evidence that the gene-gene connection is previously known. 

The goal here is to find a possible explanation for why we see a strong correlation/anticorrelation between pairs/groups of genes in the ORF or CRISPR profiles. All issues I have linked here are ones that have weak evidence in the knowledge graph. Therefore, any possible explanation we can come up with will likely be novel and valuable to the paper.

Make sure that you skim through the existing comments in the issues to get an idea of what we already know.

Let's use this issue to have a general discussion about these issues.

**Comment by shntnu** [comment]
Pretty sure yes; I will close now but will tag @AnneCarpenter @niranjchandrasekaran to keep them posted
