### ISSUE TITLE
Add links to further resources

### ISSUE THREAD

**Issue by afermg** [broadinstitute/2023_12_JUMP_data_only_vignettes#44]
Once they are public, add the links to the papers corresponding to [these lines](https://github.com/broadinstitute/2023_12_JUMP_data_only_vignettes/blob/main/index.md?plain=1#L38-L39) on the readme.

**Comment by AnneCarpenter** [comment]
done, for JUMP data prod biorxiv, added "coming soon" for MorphMap, should be able to update in a few weeks!
