### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by AnneCarpenter** [broadinstitute/2023_12_JUMP_data_only_vignettes#48]
I'm sorry - i gave it five minutes but couldn't figure out how the link for this is broken:

You can find more details [here](https://github.com/broadinstitute/2023_12_JUMP_data_only_vignettes/blob/main/explanations/quirk_details.md).

at the bottom of this page:
https://broadinstitute.github.io/2023_12_JUMP_data_only_vignettes/explanations/data_description.html

when it looks like the same syntax as for 0_how-to.md upstream on the page.

**Comment by afermg** [comment]
Fixed on 4052f95411d9d62d8290379b07f6b0e0f4bd6b73
