### ISSUE TITLE
HOOK2 opposite effect than PAFAH1B1, NDE1, NDEL1: exploration for MorphMap paper (ORF)

### ISSUE THREAD

**Issue by AnneCarpenter** [broadinstitute/2023_12_JUMP_data_only_vignettes#5]
We found a tight cluster of PAFAH1B1, NDE1, NDEL1, and those 3 have the opposite morphological effect to the gene HOOK2.
Emailed Sivaram V.S. Mylavarapu Nov 29, 2023: https://mail.google.com/mail/u/0/#sent/KtbxLwgxBKKHZtcxwBdZCLKMjxlVNDmDqV 
No reply so then I emailed Jan 5: [msharma@iisermohali.ac.in](mailto:msharma@iisermohali.ac.in) because at least they studied HOOK2: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6400558/

**Comment by AnneCarpenter** [comment]
@niranjchandrasekaran can you please confirm May 24 is the latest/correct correlation matrix and KG values for this set? 
(note to self: it's ok there's no CRISPR correlation matrix because only one gene of this set was tested in CRISPR). 

Reading thru all this and the paragraph in the paper, I think this story is 'done' but may need reconciling of final figures with the text that describes them in the paper.

**Comment by niranjchandrasekaran** [comment]
> can you please confirm May 24 is the latest/correct correlation matrix and KG values for this set?

Can confirm.

**Comment by niranjchandrasekaran** [comment]
This story was included in the morphmap paper.
