### ISSUE TITLE
SLC or OR gene superfamilies: exploration for MorphMap paper (ORFs, need to check CRISPR)

### ISSUE THREAD

**Issue by AnneCarpenter** [broadinstitute/2023_12_JUMP_data_only_vignettes#6]
**Anna Greka** - Anne emailed (who works on ion channels) to see if she knows someone to talk with - Dec 15 https://mail.google.com/mail/u/0/#sent/KtbxLzfphpSXKvqjLksXdBkZFbLTKPBNnB

**Eitan Hoch** - We could contact (working on a single SLC gene): https://mail.google.com/mail/u/0/popout?ver=1uc31lzgyq4bq&q=slc%20genes&qs=true&qid=7AD9A531-CA56-4FEA-BCA3-F3E12F0B2C4C&aqid=0EFF949C-A964-4282-B723-90BA8849E4E6&search=query&cmembership=1&silk=E6C0CD25-2274-41A5-AD3C-A6E239256E92&th=%23thread-f%3A1562673576686256012&qt=city.1.gene.1.genes.1.genetic.1.genetics.1.genome.1.lake.1.salt.1.slc.1&cvid=1

Found one paper: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3082935/

Could email the JUMP cell painting email list

**Comment by niranjchandrasekaran** [comment]
We will discuss the exploration of the story in [this doc](https://docs.google.com/document/d/1zKkDpBWbb3NnQhlX34LEWuuZxy5Rotre5uuuBMTxvxY/edit?usp=sharing) (private link)

**Comment by AnneCarpenter** [comment]
See our draft paragraph here in the paper: https://docs.google.com/document/d/160QYCeJXMJMPgvYcirkkKaY99r6dZq6FMqYGE61CfFc/edit#bookmark=id.l2u8zkksn0ba

**Comment by dselinger-plex** [comment]
Adding a test comment here.

**Comment by niranjchandrasekaran** [comment]
Included in the morphmap paper
