### ISSUE TITLE
Find gene connections [ORF+CRISPR both] to pursue: exploration for MorphMap paper

### ISSUE THREAD

**Issue by AnneCarpenter** [broadinstitute/2023_12_JUMP_data_only_vignettes#7]
Here is the updated list they provided Dec 15 2023. 

We are generally interested to find gene pairs where:
- there is a strong Cell Painting ORF pos or neg correlation (column E: ORF_similarity_abs)
- there is NOT a strong knowledge graph connection (there are 4 KG-only models, columns F-I)

We already found many connections between  SLC and OR gene families and will pursue those (https://github.com/broadinstitute/2023_12_JUMP_data_only_vignettes/issues/6) but we would like more.

Here is the email thread in Anne's email "Broad/Evotec collaboration on MorphMap & knowledge graphs" https://mail.google.com/mail/u/0/#inbox/FMfcgzGtwDFhnZvdwPWGMLLbdpgNZBSM with excel file 

Here are the meeting notes: https://docs.google.com/document/d/1iIwJ1V5ig8KtTD7P0vV-GH16f-AvprqU/edit

[MorphMap_gene_gene_scoring_data.xlsx](https://github.com/broadinstitute/2023_12_JUMP_data_only_vignettes/files/13689808/MorphMap_gene_gene_scoring_data.xlsx)

**Comment by niranjchandrasekaran** [comment]
Separate issues were created for the new connections in this issue and those were included in the morphmap paper
